#!/usr/bin/env bash

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# down the last running theme
if [[ -f "/tmp/leftwm-theme-down" ]]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi

ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# set custom resolution
if [[ -x "$(command -v xrandr)" ]]; then
  . "$SCRIPTPATH/hooks/xrandr.sh"
fi
 
# boot picom or compton if it exists
if [[ -x "$(command -v picom)" ]]; then
  picom &> /dev/null &
elif [[ -x "$(command -v compton)" ]]; then
  compton &> /dev/null &
fi

# set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# set background
if [[ -x "$(command -v feh)" ]]; then
  feh --bg-scale $SCRIPTPATH/background.jpg
fi

# keyboard layout
localectl --no-convert set-x11-keymap br
localectl set-keymap br-abnt2
localectl set-locale LANG=pt_BR.UTF-8
